version: '3.4'

services:
  console-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    restart: unless-stopped
