name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t console-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') # Exécute uniquement pour les tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key && chmod 600 lightsail_key

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Save and Deploy Docker Image
        run: |
          docker save console-app:latest | ssh -i lightsail_key ubuntu@${{ secrets.LIGHTSAIL_IP }} \
          'docker load && docker ps -q --filter "name=console-app" | grep -q . && docker stop console-app && docker rm console-app || true && docker run -d -p 3000:80 --name console-app console-app:latest'
